from biotite.structure.atoms import AtomArray
from numpy import ndarray


class DsspApp:
    def __init__(self, atom_array: AtomArray, bin_path: str = 'dssp', mute: bool = True) -> None: ...
    @staticmethod
    def annotate_sse(atom_array: AtomArray, bin_path: str = 'dssp') -> ndarray: ...
    def evaluate(self) -> None: ...
    def run(self) -> None: ...
