# This source code is part of the Biotite package and is distributed
# under the 3-Clause BSD License. Please see 'LICENSE.rst' for further
# information.

from typing import Union, Tuple, MutableMapping, Iterable, Iterator, TextIO
from ....file import TextFile


class FastaFile(TextFile, MutableMapping[str, str]):
    def __init__(self, chars_per_line: int = 80) -> None: ...
    def read(self, file: Union[str, TextIO]) -> None: ...
    def __setitem__(self, header: str, seq_str: str) -> None: ...
    def __getitem__(self, header: str) -> str: ...
    def __delitem__(self, header: str) -> None: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[Tuple[str, str]]: ...
