from typing import (
    Iterator,
    Tuple,
)


class FastaFile:
    def __delitem__(self, header: str) -> None: ...
    def __getitem__(self, header: str) -> str: ...
    def __init__(self, chars_per_line: int = 80) -> None: ...
    def __iter__(self) -> Iterator[Tuple[str, str]]: ...
    def __setitem__(self, header: str, seq_str: str) -> None: ...
    def _find_entries(self) -> None: ...
    def read(self, file: str) -> None: ...
