__all__ = ["KmerTable", "BucketKmerTable"]

from collections.abc import Iterable, Iterator
from typing import Any, Generic
import numpy as np
from biotite.sequence.align.kmeralphabet import KmerAlphabet
from biotite.sequence.align.kmersimilarity import SimilarityRule
from biotite.sequence.alphabet import Alphabet
from biotite.sequence.sequence import Sequence
from biotite.typing import C2, C3, C4, M, N, NDArray1, NDArray2, S

class KmerTable(Generic[S]):
    def __init__(self, kmer_alphabet: KmerAlphabet[S]) -> None: ...
    @property
    def kmer_alphabet(self) -> KmerAlphabet[S]: ...
    @property
    def alphabet(self) -> Alphabet[S]: ...
    @property
    def k(self) -> int: ...
    @staticmethod
    def from_sequences(
        k: int,
        sequences: Iterable[Sequence[S]],
        ref_ids: Iterable[int] | None = None,
        ignore_masks: Iterable[NDArray1[N, np.bool_]] | None = None,
        alphabet: Alphabet[S] | None = None,
        spacing: str | list[int] | NDArray1[N, np.integer] | None = None,
    ) -> KmerTable[S]: ...
    @staticmethod
    def from_kmers(
        kmer_alphabet: KmerAlphabet[S],
        kmers: Iterable[NDArray1[N, np.int64]],
        ref_ids: Iterable[int] | None = None,
        masks: Iterable[NDArray1[N, np.bool_]] | None = None,
    ) -> KmerTable[S]: ...
    @staticmethod
    def from_kmer_selection(
        kmer_alphabet: KmerAlphabet[S],
        positions: Iterable[NDArray1[N, np.uint32]],
        kmers: Iterable[NDArray1[N, np.int64]],
        ref_ids: Iterable[int] | None = None,
    ) -> KmerTable[S]: ...
    @staticmethod
    def from_tables(tables: Iterable[KmerTable[S]]) -> KmerTable[S]: ...
    @staticmethod
    def from_positions(
        kmer_alphabet: KmerAlphabet[S],
        kmer_positions: dict[int, NDArray2[N, C2, np.integer]],
    ) -> KmerTable[S]: ...
    def match_table(
        self,
        table: KmerTable[S],
        similarity_rule: SimilarityRule | None = None,
    ) -> NDArray2[M, C4, np.uint32]: ...
    def match(
        self,
        sequence: Sequence[S],
        similarity_rule: SimilarityRule | None = None,
        ignore_mask: NDArray1[N, np.bool_] | None = None,
    ) -> NDArray2[M, C3, np.uint32]: ...
    def match_kmer_selection(
        self,
        positions: NDArray1[N, np.uint32],
        kmers: NDArray1[N, np.int64],
    ) -> NDArray2[M, C3, np.uint32]: ...
    def count(
        self, kmers: NDArray1[N, np.int64] | None = None
    ) -> NDArray1[N, np.int64]: ...
    def get_kmers(self) -> NDArray1[N, np.int64]: ...
    def __getitem__(self, kmer: int) -> NDArray2[N, C2, np.uint32]: ...
    def __len__(self) -> int: ...
    def __contains__(self, kmer: object) -> bool: ...
    def __iter__(self) -> Iterator[int]: ...
    def __reversed__(self) -> Iterator[int]: ...
    def __eq__(self, item: object) -> bool: ...
    def __str__(self) -> str: ...
    def __getnewargs_ex__(self) -> tuple[tuple, dict]: ...
    def __getstate__(self) -> Any: ...
    def __setstate__(self, state: Any) -> None: ...

class BucketKmerTable(Generic[S]):
    def __init__(self, n_buckets: int, kmer_alphabet: KmerAlphabet[S]) -> None: ...
    @property
    def kmer_alphabet(self) -> KmerAlphabet[S]: ...
    @property
    def alphabet(self) -> Alphabet[S]: ...
    @property
    def k(self) -> int: ...
    @property
    def n_buckets(self) -> int: ...
    @staticmethod
    def from_sequences(
        k: int,
        sequences: Iterable[Sequence[S]],
        ref_ids: Iterable[int] | None = None,
        ignore_masks: Iterable[NDArray1[N, np.bool_]] | None = None,
        alphabet: Alphabet[S] | None = None,
        spacing: str | list[int] | NDArray1[N, np.integer] | None = None,
        n_buckets: int | None = None,
    ) -> BucketKmerTable[S]: ...
    @staticmethod
    def from_kmers(
        kmer_alphabet: KmerAlphabet[S],
        kmers: Iterable[NDArray1[N, np.int64]],
        ref_ids: Iterable[int] | None = None,
        masks: Iterable[NDArray1[N, np.bool_]] | None = None,
        n_buckets: int | None = None,
    ) -> BucketKmerTable[S]: ...
    @staticmethod
    def from_kmer_selection(
        kmer_alphabet: KmerAlphabet[S],
        positions: Iterable[NDArray1[N, np.uint32]],
        kmers: Iterable[NDArray1[N, np.int64]],
        ref_ids: Iterable[int] | None = None,
        n_buckets: int | None = None,
    ) -> BucketKmerTable[S]: ...
    @staticmethod
    def from_tables(
        tables: Iterable[BucketKmerTable[S]],
    ) -> BucketKmerTable[S]: ...
    def match_table(
        self,
        table: BucketKmerTable[S],
        similarity_rule: SimilarityRule | None = None,
    ) -> NDArray2[M, C4, np.uint32]: ...
    def match(
        self,
        sequence: Sequence[S],
        similarity_rule: SimilarityRule | None = None,
        ignore_mask: NDArray1[N, np.bool_] | None = None,
    ) -> NDArray2[M, C3, np.uint32]: ...
    def match_kmer_selection(
        self,
        positions: NDArray1[N, np.uint32],
        kmers: NDArray1[N, np.int64],
    ) -> NDArray2[M, C3, np.uint32]: ...
    def count(self, kmers: NDArray1[N, np.int64]) -> NDArray1[N, np.int64]: ...
    def get_kmers(self) -> NDArray1[N, np.int64]: ...
    def __getitem__(self, kmer: int) -> NDArray2[N, C2, np.uint32]: ...
    def __len__(self) -> int: ...
    def __eq__(self, item: object) -> bool: ...
    def __str__(self) -> str: ...
    def __getnewargs_ex__(self) -> tuple[tuple, dict]: ...
    def __getstate__(self) -> Any: ...
    def __setstate__(self, state: Any) -> None: ...
