__all__ = ["KmerAlphabet"]

from collections.abc import Iterable, Iterator
from collections.abc import Sequence as SequenceABC
from typing import Any, overload
import numpy as np
from biotite.sequence.alphabet import Alphabet
from biotite.typing import K, N, NDArray1, NDArray2, S

class KmerAlphabet(Alphabet[tuple[S, ...]]):
    def __init__(
        self,
        base_alphabet: Alphabet[S],
        k: int,
        spacing: str | list[int] | NDArray1[K, np.integer] | None = None,
    ) -> None: ...
    @property
    def base_alphabet(self) -> Alphabet[S]: ...
    @property
    def k(self) -> int: ...
    @property
    def spacing(self) -> NDArray1[K, np.int64] | None: ...
    def get_symbols(self) -> tuple[tuple[S, ...], ...]: ...
    def extends(self, alphabet: Alphabet[Any]) -> bool: ...
    def encode(self, symbol: Iterable[S]) -> int: ...
    def decode(self, code: int) -> SequenceABC[S]: ...
    @overload
    def fuse(self, codes: NDArray1[K, np.integer]) -> int: ...
    @overload
    def fuse(self, codes: NDArray2[N, K, np.integer]) -> NDArray1[N, np.int64]: ...
    @overload
    def split(self, kmer_code: int) -> NDArray1[K, np.uint64]: ...
    @overload
    def split(
        self, kmer_code: NDArray1[N, np.integer]
    ) -> NDArray2[N, K, np.uint64]: ...
    def kmer_array_length(self, length: int) -> int: ...
    def create_kmers(
        self, seq_code: NDArray1[N, np.unsignedinteger]
    ) -> NDArray1[K, np.int64]: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __eq__(self, item: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[tuple[S, ...]]: ...
    def __contains__(self, symbol: object) -> bool: ...
