__all__ = ["Tree", "TreeNode", "as_binary", "TreeError"]

from collections.abc import Iterable
from typing import overload
import networkx as nx
import numpy as np
from biotite.copyable import Copyable
from biotite.typing import K, NDArray1

class Tree(Copyable):
    def __init__(self, root: TreeNode) -> None: ...
    def __copy_create__(self) -> Tree: ...
    @property
    def root(self) -> TreeNode: ...
    @property
    def leaves(self) -> list[TreeNode]: ...
    def as_graph(self) -> nx.Graph: ...
    def get_distance(
        self, index1: int, index2: int, topological: bool = False
    ) -> float: ...
    def to_newick(
        self,
        labels: list[str] | None = None,
        include_distance: bool = True,
        round_distance: int | None = None,
    ) -> str: ...
    @staticmethod
    def from_newick(newick: str, labels: list[str] | None = None) -> Tree: ...
    def __str__(self) -> str: ...
    def __len__(self) -> int: ...
    def __eq__(self, item: object) -> bool: ...
    def __hash__(self) -> int: ...

class TreeNode:
    def __init__(
        self,
        children: Iterable[TreeNode] | None = None,
        distances: Iterable[float] | None = None,
        index: int | None = None,
    ) -> None: ...
    def copy(self) -> TreeNode: ...
    @property
    def index(self) -> int | None: ...
    @property
    def children(self) -> tuple[TreeNode, ...]: ...
    @property
    def parent(self) -> TreeNode | None: ...
    @property
    def distance(self) -> float: ...
    def is_leaf(self) -> bool: ...
    def is_root(self) -> bool: ...
    def as_root(self) -> None: ...
    def distance_to(self, node: TreeNode, topological: bool = False) -> float: ...
    def lowest_common_ancestor(self, node: TreeNode) -> TreeNode: ...
    def get_indices(self) -> NDArray1[K, np.integer]: ...
    def get_leaves(self) -> list[TreeNode]: ...
    def get_leaf_count(self) -> int: ...
    def to_newick(
        self,
        labels: list[str] | None = None,
        include_distance: bool = True,
        round_distance: int | None = None,
    ) -> str: ...
    @staticmethod
    def from_newick(
        newick: str, labels: list[str] | None = None
    ) -> tuple[TreeNode, float, int | None]: ...
    def __str__(self) -> str: ...
    def __eq__(self, item: object) -> bool: ...
    def __hash__(self) -> int: ...

@overload
def as_binary(tree_or_node: Tree) -> Tree: ...
@overload
def as_binary(tree_or_node: TreeNode) -> TreeNode: ...

class TreeError(Exception): ...
