from typing import Callable


def requires_state(app_state: int) -> Callable: ...


class Application:
    def __init__(self) -> None: ...
    def evaluate(self) -> None: ...
    def get_app_state(self) -> AppState: ...
