class LocalApp:
    def __init__(self, bin_path: str, mute: bool = True) -> None: ...
    def clean_up(self) -> None: ...
    def evaluate(self) -> None: ...
    def is_finished(self) -> bool: ...
    def run(self) -> None: ...
    def wait_interval(self) -> float: ...
