from biotite.sequence.seqtypes import ProteinSequence
from typing import List


class MSAApp:
    def __init__(
        self,
        sequences: List[ProteinSequence],
        bin_path: None = None,
        mute: bool = True
    ) -> None: ...
    def evaluate(self) -> None: ...
    def get_input_file_path(self) -> str: ...
    def get_output_file_path(self) -> str: ...
    def run(self) -> None: ...
