---
name: "TEMP"

on:
  push:
    branches:
      - "main"

jobs:
  upload-docs:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Install dependencies for documentation upload
      run: pip install requests
    - uses: actions/checkout@v4
    - run: mkdir dist
    - run: wget https://github.com/biotite-dev/biotite/releases/download/v1.0.1/doc.zip -O dist/doc.zip
    - name: Unzip documentation
      run: unzip dist/doc.zip -d build
    - name: Assemble multi-version documentation
      run: >
        python .github/workflows/multiversion_docs.py
        build/doc/_static/switcher.json
        dist/assembled_doc
    - name: Upload documentation to website
      uses: easingthemes/ssh-deploy@v5.1.0
      with:
        SSH_PRIVATE_KEY: ${{ secrets.DOCS_PRIVATE_KEY }}
        REMOTE_HOST: ${{ secrets.DOC_HOST }}
        REMOTE_USER: ${{ secrets.DOC_USER }}
        SOURCE: "dist/assembled_doc"
        TARGET: "biotite"
